pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'pceqzg-recover' } 
    stages {
        stage('Test') {
            options { timeout(time: 360, unit: 'SECONDS') }
            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}
